implement updateValue method & tests
janis-commerce/aws-secrets-manager pull request #1
Opened 2023-04-06 15:49 UTC by moruezabal

[Tarea](https://janiscommerce.atlassian.net/browse/JSS-5) / [Subtarea](https://janiscommerce.atlassian.net/browse/JSS-12)

### Descripción:
Se deberá agregar un nuevo metodo ([UpdateSecret](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SecretsManager.html#updateSecret-property)) al package de  (el metodo se debera llamar updateValue para tener concordancia con el getValue)

### Solución: 
- Agregué el método updateValue() que recibe el string en base64. para actualizar el secret mediante el método updateSecret() de AWS. Después setea en el caché los nuevos valores de VersionId y VersionStage recibidos.
- Agregué en el wrapper el método updateSecret para su fácil uso.
- Añadidos los tests correspondientes

2023-04-09 12:48 UTC, manuelvilche commented
Recibe el string en base64?? Ósea que todo el mundo que lo use lo va a tener que convertir antes de guardar?? No te parece más conveniente que hagamos la conversión en el package, así ya le sacamos un peso de encima a todo el que use el package!?? @moruezabal

2023-04-10 18:54 UTC, Nataniel4 commented on lib/secret-handler.js
> +			const newValuePromise = await AWS.secretsManager.updateSecret(params);
Esta charlado por Slack pero lo dejo asentado aca tambien, no esta bueno lo de la doble promesa, seguramente esto funcione directamente con el primer `await`

2023-04-10 18:54 UTC, Nataniel4 requested changes
Revisar lo de la doble promesa

2023-04-12 21:17 UTC, moruezabal commented on lib/secret-handler.js
> +			const newValuePromise = await AWS.secretsManager.updateSecret(params);
He usado otros métodos del V3 del SDK de Amazon y funcionan con el primer await. Ahí quedó arreglado, y agregué el encoding de la clave recibida

2023-04-17 13:40 UTC, Nataniel4 approved these changes
Aprobado!

2023-04-18 21:45 UTC, gastonpereyra commented on lib/secret-handler.js
> +			const valuePromise = AWS.secretsManager.getSecretValue(params);
MMMMMMMMMMMMMMMMMM..

De donde sale la info que esto no es async ?

2023-04-18 21:47 UTC, gastonpereyra commented on lib/secret-handler.js
> +			const newValuePromise = AWS.secretsManager.updateSecret(params);
Lo mismo con el otro comentario, qué tan seguro estamos que no es async ?

En la lógica que actualiza cosas en un server de AWS esto debería ser async.

2023-04-18 21:48 UTC, gastonpereyra requested changes
Se pudo probar en algún lado esto ? Para mi tiene la pinta que no va a funcionar.

En caso de no haberlo probado buscaria la forma de intentar hacerlo antes de avanzar para no romper todo

2023-04-19 20:37 UTC, moruezabal commented on lib/secret-handler.js
> +			const newValuePromise = AWS.secretsManager.updateSecret(params);
[
](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-secrets-manager/classes/updatesecretcommand.html)El método de la SDK de AWS en su V3 devuelve una promesa, lo que se hace es conservarla en esa variable para setear el caché porque según @jormaechea  Para que no se rompa el cache, lo que hay que hacer es guardar promises allí. 
Luego se awaitea esa promesa para retornar su valor real. Mismo escenario para la otra función.
Para [este desarrollo](https://bitbucket.org/fizzmodsrl/janis-storage-service/pull-requests/4) estuve utilizando el client cloudFront del SDK de AWS (V3) para actualizar las publicKeys, y está probado el uso y resolución de las promesas.

2023-04-19 21:24 UTC, gastonpereyra commented on lib/secret-handler.js
> +			const newValuePromise = AWS.secretsManager.updateSecret(params);
Cloud Front es otro client.. aca estas usando Secret Manager.

Estaria bueno hacer alguna prueba aunque sea un poco informal, para ver que esta funcionando como se espera.. porque ahora tendriamos que confiar que los packages diferentes funcionen igual..

2023-04-19 21:29 UTC, gastonpereyra commented on lib/secret-handler.js
> +			const newValuePromise = AWS.secretsManager.updateSecret(params);
Por otra parte, estaria bueno meter las explicaciones como lo de la Cache y otras en los tickets a modo de documentación técnica, porque no hay nada.. y algunas de estas cosas son interesantes de saber, y pueden ayudarnos para cuando haya que volver a este package.

2023-04-21 19:13 UTC, moruezabal commented
Probé el package insertandolo como un helper en la tarea que requería el método updateValue(), y el método getSecretValue(), respondió correctamente, una promesa que es seteada en el caché. Luego al awaitear la promesa, retorna el objeto de respuesta:
`{
  Name: "storage",
  VersionId: "409919c9-826f-4cf9-bf8e-bcf4d50ed49d",
  ARN: "arn:aws:secretsmanager:us-east-1:157255757427:secret:storage-mDekIe",
  $metadata: {
      httpStatusCode: 200,
      requestId: "fc58f80f-dd3d-4483-8793-8f0a2ac39169",
      attempts: 1,
      totalRetryDelay: 0
    },
}`
[Log de Lambda RotateCredentials en Storage](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252FJanisStorageService-beta-RotateCredentials/log-events/2023$252F04$252F21$252F$255B$2524LATEST$255Dd02f1df14fe3459fa3706467ecc17214)

2023-04-21 21:54 UTC, gastonpereyra approved these changes

2023-04-25 20:45 UTC, moruezabal commented
@manuelvilche Acorde como ajusté en la otra tarea, ahora updateValue() espera el secret entero en forma de objeto.
El método ahora parsea la privateKey en base 64, y pasa el secreto a guardar a String, para almacenarlo en secretString.
Otra alternativa era que updateValue() recibiera el secret ya convertido en JSON, pero me pareció más usable esta.

2023-04-26 19:28 UTC, moruezabal commented
@manuelvilche ahí quedó contemplado el secretBinary. Lo que se busca hacer es gettear el secreto actual, para saber si está guardando el secreto en formato string o binario, y depende de esto, manda la prop correspondiente en los parametros de la actualización.
Agregué una validación al principio para asegurarse que hay un objeto a parsear.
El formato del privateKey no se controla, ya que analizandolo con Argenis, debería ser responsabilidad del usuario de mandarla encodeado en base64, y para evitar un doble formateo.

2023-05-22 18:43 UTC, merged